---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: gotify/server-arm7
  # repository: gotify/server-arm64
  # repository: gotify/server
  pullPolicy: IfNotPresent
  tag: "2.0.23"

secret:
  user: "admin"
  pass: "admin"

# See more environment variables in the gotify documentation
# https://gotify.net/docs/config#environment-variables
env:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TZ: "America/Los_Angeles"
  GOTIFY_SERVER_PORT: "80"
  GOTIFY_SERVER_KEEPALIVEPERIODSECONDS: "0"
  GOTIFY_SERVER_LISTENADDR: ""
  GOTIFY_SERVER_SSL_ENABLED: "false"
  GOTIFY_SERVER_SSL_REDIRECTTOHTTPS: "true"
  GOTIFY_SERVER_SSL_LISTENADDR: ""
  GOTIFY_SERVER_SSL_PORT: "443"
  GOTIFY_SERVER_SSL_CERTFILE: ""
  GOTIFY_SERVER_SSL_CERTKEY: ""
  GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED: "false"
  GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS: "false"
  GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE: "certs"
  # lists are a little weird but do-able (:
  # GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS: "- mydomain.tld\n- myotherdomain.tld"
  GOTIFY_SERVER_RESPONSEHEADERS: "X-Custom-Header: \"custom value\""
  # GOTIFY_SERVER_CORS_ALLOWORIGINS: "- \".+.example.com\"\n- \"otherdomain.com\""
  # GOTIFY_SERVER_CORS_ALLOWMETHODS: "- \"GET\"\n- \"POST\""
  # GOTIFY_SERVER_CORS_ALLOWHEADERS: "- \"Authorization\"\n- \"content-type\""
  # GOTIFY_SERVER_STREAM_ALLOWEDORIGINS: "- \".+.example.com\"\n- \"otherdomain.com\""
  GOTIFY_SERVER_STREAM_PINGPERIODSECONDS: "45"
  GOTIFY_DATABASE_DIALECT: "sqlite3"
  GOTIFY_DATABASE_CONNECTION: "data/gotify.db"
  GOTIFY_PASSSTRENGTH: "10"
  GOTIFY_UPLOADEDIMAGESDIR: "data/images"
  GOTIFY_PLUGINSDIR: "data/plugins"

service:
  port:
    port: 80

ingress:
  enabled: false

persistence:
  data:
    enabled: false
    emptyDir: false
    mountPath: /app/data
    accessMode: ReadWriteOnce
    size: 1Gi
