---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/nicholaswilde/installer
  pullPolicy: IfNotPresent
  tag: "version-0.2.9"

secret: {}
  # USER: ""
  # GH_TOKEN: ""

# See more environment variables in the installer documentation
# https://github.com/nicholaswilde/docker-installer
env: {}
  # TZ: ""

service:
  port:
    port: 3000

ingress:
  enabled: false
