---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/nicholaswilde/twtxt
  pullPolicy: IfNotPresent
  tag: "version-0.1.1"

secret:
  COOKIE_SECRET: supersecretchangeme

# See more environment variables in the twtxt documentation
# https://github.com/nicholaswilde/docker-twtxt
env:
  TZ: "America/Los_Angeles"
  # PUID: "1000"
  # PGID: "1000"
  OPEN_PROFILES: "true"
  OPEN_REGISTRATIONS: "true"

service:
  port:
    port: 8000

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi
