---
apiVersion: v2
appVersion: "154c581"
version: 0.1.1
name: golinks
description: A web app that allows you to create smart bookmarks, commands and aliases by pointing your web browser's default search engine at a running instance.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/golinks"
icon: ""
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - search
  - browser
  - bookmarks
  - smart-bookmarks
  - golinks
sources:
  - https://github.com/prologic/golinks
  - https://github.com/nicholaswilde/docker-golinks
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bumped tag to 154c581-ls2
  artifacthub.io/images: |
    - name: golinks
      image: ghcr.io/nicholaswilde/golinks:154c581-ls2
