---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/nicholaswilde/golinks
  pullPolicy: IfNotPresent
  tag: "version-154c581"

secret: {}

# See more environment variables in the golinks documentation
# https://github.com/nicholaswilde/docker-golinks
env: {}
  # TZ: "America/Los_Angeles"
  # PUID: "1000"
  # PGID: "1000"
  # SUGGEST=https://suggestqueries.google.com/complete/search?client=firefox&q=%s `# optional` \
  # TITLE=Search `# optional` \
  # URL=https://www.google.com/search?q=%s&btnK

service:
  port:
    port: 8000

ingress:
  enabled: false

persistence:
  app:
    enabled: false
    emptyDir: false
    mountPath: /app
    accessMode: ReadWriteOnce
    size: 1Gi
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi
