---
# Default values for golinks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/nicholaswilde/golinks
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "154c581-ls1"

secret: {}

env:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TZ: "America/Los_Angeles"
  # PUID: "1000"
  # PGID: "1000"
  # SUGGEST=https://suggestqueries.google.com/complete/search?client=firefox&q=%s `# optional` \
  # TITLE=Search `# optional` \
  # URL=https://www.google.com/search?q=%s&btnK

service:
  port:
    port: 8000

ingress:
  enabled: true
  hosts:
    - host: "golinks.192.168.1.203.nip.io"
      paths:
        - path: /
          # Ignored if not kubeVersion >= 1.14-0
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  app:
    enabled: false
    emptyDir: false
    mountPath: /app
    ## Template downloads data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ##
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    # existingClaim: your-claim
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false
