---
apiVersion: v2
appVersion: 14.0
version: 0.1.1
name: odoo
description: All-in-one business software. Beautiful. Easy-to-use. CRM, Accounting, PM, HR, Procurement, Point of Sale, MRP, Marketing, etc.
type: application
homepage: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/odoo"
icon: "https://pbs.twimg.com/profile_images/970608340014419969/1bpCWJhS_400x400.jpg"
dependencies:
  - name: common
    version: ~0.1.7
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - odoo
  - crm
  - pm
  - hr
  - accounting
  - mrp
  - marketing
sources:
  - https://www.odoo.com/
  - https://hub.docker.com/repository/docker/nicholaswilde/odoo
maintainers:
  - name: Nicholas Wilde
    email: ncwilde43@gmail.com
