---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/nicholaswilde/odoo
  pullPolicy: IfNotPresent
  tag: "version-14.0"

secret: {}
  # USER: "odoo"
  # PASSWORD: "myodoo"

# See more environment variables in the odoo documentation
# https://github.com/nicholaswilde/docker-odoo
env: {}
  # HOST: "odoo-db"

service:
  port:
    port: 8069
  additionalPorts:
    - name: "8071-tcp"
      port: 8071
      protocol: TCP
    - name: "8072-tcp"
      port: 8072
      protocol: TCP

ingress:
  enabled: false

persistence:
  odoo:
    enabled: false
    emptyDir: false
    mountPath: /var/lib/odoo
    accessMode: ReadWriteOnce
    size: 1Gi
  addons:
    enabled: false
    emptyDir: false
    mountPath: /mnt/extra-addons
    accessMode: ReadWriteOnce
    size: 1Gi

# Enable postgres
# https://github.com/nicholaswilde/helm-charts/blob/main/charts/postgres/values.yaml
postgres:
  enabled: false
  secret:
    POSTGRES_PASSWORD: odoo
  env:
    POSTGRES_DB: postgres
    POSTGRES_USER: odoo
  fullnameOverride: odoo-postgres
