---
remote: origin
target-branch: main
helm-extra-args: --timeout 600s
chart-dirs:
  - charts
excluded-charts:
  - charts/common
chart-repos:
  - k8s-at-home-libraries=https://library-charts.k8s-at-home.com
  - k8s-at-home=https://k8s-at-home.com/charts
  - nicholaswilde=https://nicholaswilde.github.io/helm-charts/
