---
apiVersion: v2
appVersion: v2.0.1
version: 1.0.0
name: papermerge
description: Designed for scanned documents. Perfect software that will help you reduce paper clutter and keep your business organized.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/papermerge"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/papermerge-icon.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
  - name: mariadb
    version: ~1.0.3
    repository: https://nicholaswilde.github.io/helm-charts/
    condition: mariadb.enabled
  - name: postgres
    version: ~0.1.0
    repository: https://nicholaswilde.github.io/helm-charts/
    condition: postgres.enabled
keywords:
  - paper
  - merge
  - document
  - scan
  - scanner
sources:
  - https://www.papermerge.com/
  - https://hub.docker.com/r/linuxserver/papermerge
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Add mariadb support.
    - Add postgres support.
    - A lot of config has changed.
  artifacthub.io/images: |
    - name: papermerge
      image: ghcr.io/linuxserver/papermerge:v2.0.1-ls5
