---
apiVersion: v2
appVersion: v2.0.0rc35
version: 0.3.0
name: papermerge
description: Designed for scanned documents. Perfect software that will help you reduce paper clutter and keep your business organized.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/papermerge"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/papermerge-icon.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - paper
  - merge
  - document
  - scan
  - scanner
sources:
  - https://www.papermerge.com/
  - https://hub.docker.com/r/linuxserver/papermerge
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bumped tag to v2.0.0rc35-ls27
  artifacthub.io/images: |
    - name: papermerge
      image: ghcr.io/linuxserver/papermerge:v2.0.0rc35-ls27
