# See https://github.com/helm/chart-testing#configuration
remote: origin
chart-dirs:
  - charts
excluded-charts:
  - common
chart-repos: []
helm-extra-args: --timeout 600s
check-version-increment: true
