---
repos:
  - repo: local
    hooks:
      - id: ct-lint
        name: "Chart Test: Lint"
        language: docker_image
        pass_filenames: false
        types: ['file']
        files: '^charts/.*(\.ya?ml|\.tpl|\.helmignore|NOTES.txt)'
        entry: -u 0 quay.io/helmpack/chart-testing:v3.3.1 ct
        args:
          - lint
          - --config
          - .ct.yaml
      - id: shellcheck
        name: Test shell scripts with shellcheck
        description: Shell scripts conform to shellcheck
        entry: koalaman/shellcheck:latest
        language: docker_image
        types: [shell]
        args: []
        additional_dependencies: [shellcheck]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: helmlint
