---
apiVersion: v2
appVersion: 1.29.1
version: 0.2.20
name: cloud9
description: A complete web based IDE with terminal access
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/cloud9"
icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cloud9.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - cloud9
  - ide
  - terminal
  - web
sources:
  - https://aws.amazon.com/cloud9/
  - https://github.com/c9/core
  - https://hub.docker.com/r/linuxserver/cloud9
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bumped tag to 1.29.1-ls76
  artifacthub.io/images: |
    - name: cloud9
      image: ghcr.io/linuxserver/cloud9:1.29.1-ls76
