---
apiVersion: v2
appVersion: "900b76a"
version: 0.1.0
name: wiki
description: A self-hosted well uh wiki engine or content management system.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/wiki"
icon: ""
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - wiki
  - web
  - blog
  - cms
  - app
sources:
  - https://github.com/prologic/wiki
  - https://github.com/nicholaswilde/docker-wiki
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Initial release.
  artifacthub.io/images: |
    - name: wiki
      image: ghcr.io/nicholaswilde/wiki:900b76a-ls1
