---
apiVersion: v2
appVersion: "1.2"
version: 1.0.0
name: booksonic
description: The selfhosted audiobook server
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/booksonic"
icon: "http://booksonic.org/assets/img/booksonic.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - audio
  - audiobook
  - server
  - book
sources:
  - http://booksonic.org/
  - https://hub.docker.com/r/linuxserver/booksonic
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Bump tag to 1.2-ls114
    - kind: changed
      description: Simplify values.yaml
    - kind: removed
      description: secret from values.yaml
  artifacthub.io/images: |
    - name: booksonic
      image: ghcr.io/linuxserver/booksonic:1.2-ls114
