---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/booksonic
  pullPolicy: IfNotPresent
  tag: "version-1.2"

# See more environment variables in the booksonic documentation
# https://github.com/linuxserver/docker-booksonic#parameters
env:
  TZ: "America/Los_Angeles"
  PUID: "1000"
  PGID: "1000"
  CONTEXT_PATH: "url-base"

service:
  port:
    port: 4040

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
  audiobooks:
    enabled: false
    emptyDir: false
    mountPath: /audiobooks
    accessMode: ReadWriteOnce
    size: 1Gi
  podcasts:
    enabled: false
    emptyDir: false
    mountPath: /podcasts
    accessMode: ReadWriteOnce
    size: 1Gi
  othermedia:
    enabled: false
    emptyDir: false
    mountPath: /othermedia
    accessMode: ReadWriteOnce
    size: 1Gi
