---
# Default values for booksonic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/linuxserver/booksonic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.2-ls99"
secret: {}
env:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TZ: "America/Los_Angeles"
  PUID: "1000"
  PGID: "1000"
  CONTEXT_PATH: "url-base"
service:
  port:
    port: 4040
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
  hosts:
    - host: "booksonic.192.168.1.193.nip.io"
      paths:
        - path: "/"
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false
  audiobooks:
    enabled: false
    emptyDir: false
    mountPath: /audiobooks
    ## Template downloads data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ##
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    # existingClaim: your-claim
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
  podcasts:
    enabled: false
    emptyDir: false
    mountPath: /podcasts
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false
  othermedia:
    enabled: false
    emptyDir: false
    mountPath: /othermedia
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false
