---
apiVersion: v2
appVersion: "ee8a20c"
version: 0.1.1
name: static
description: A self-hosted static file serving app which does nothing more than just serve up static files from a mounted volume.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/static"
icon: ""
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - app
  - web
  - filesystem
  - static
sources:
  - https://github.com/prologic/static
  - https://github.com/nicholaswilde/docker-static
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bump tag to ee8a20c-ls2
  artifacthub.io/images: |
    - name: static
      image: ghcr.io/nicholaswilde/static:ee8a20c-ls2
