---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/nicholaswilde/fossil
  pullPolicy: IfNotPresent
  tag: "2.15.1-ls4"

secret: {}

# See more environment variables in the fossil documentation
# https://github.com/nicholaswilde/docker-fossil/
env: {}
  # TZ:

service:
  port:
    port: 8080

ingress:
  enabled: false

persistence:
  app:
    enabled: false
    emptyDir: false
    mountPath: /app
    accessMode: ReadWriteOnce
    size: 1Gi
