---
apiVersion: v2
appVersion: 2.5.170
version: 0.1.4
name: wikijs
description: The most powerful and extensible open source Wiki software.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/wikijs"
icon: "https://pbs.twimg.com/profile_images/1349953682134200321/WoeixlMs_400x400.jpg"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - wiki
  - js
  - javascript
  - text
  - editor
sources:
  - https://wiki.js.org/
  - https://hub.docker.com/r/linuxserver/wikijs
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Updated icon
  artifacthub.io/images: |
    - name: wikijs
      image: ghcr.io/linuxserver/wikijs:2.5.170-ls19
