---
apiVersion: v2
appVersion: "v1.5.1"
version: 0.1.2
name: babybuddy
description: Helps caregivers track sleep, feedings, diaper changes, tummy time and more to learn about and predict baby's needs without (as much) guess work.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/babybuddy"
icon: "https://github.com/babybuddy/babybuddy/raw/master/babybuddy/static_src/logo/icon.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - baby
  - buddy
  - tracker
  - parents
  - parenting
sources:
  - https://github.com/babybuddy/babybuddy
  - https://github.com/nicholaswilde/docker-babybuddy
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bumped tag to v1.5.1-ls3
  artifacthub.io/images: |
    - name: babybuddy
      image: ghcr.io/nicholaswilde/babybuddy:v1.5.1-ls3
