---
# Default values for babybuddy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/nicholaswilde/babybuddy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.5.0-ls2"

secret:
  SECRET_KEY: "password"

env:
  ALLOWED_HOSTS: '*'
  # sqlite
  DJANGO_SETTINGS_MODULE: 'babybuddy.settings.base'
  # db
  # DJANGO_SETTINGS_MODULE: 'babybuddy.settings.docker'
  TIME_ZONE: America/Los_Angeles
  DEBUG: "false"

service:
  port:
    port: 8000

ingress:
  enabled: true
  hosts:
    - host: "babybuddy.192.168.1.203.nip.io"
      paths:
        - path: /
          # Ignored if not kubeVersion >= 1.14-0
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  data:
    enabled: false
    emptyDir: false
    mountPath: /app/data
    ## Template downloads data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ##
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    # existingClaim: your-claim
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
  media:
    enabled: false
    emptyDir: false
    mountPath: /app/media
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false
