---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: nicholaswilde/babybuddy
  pullPolicy: IfNotPresent
  tag: "v1.6.0-ls6"

secret:
  SECRET_KEY: "password"

# See more environment variables in the babybuddy documentation
# https://github.com/babybuddy/babybuddy#configuration
env:
  ALLOWED_HOSTS: '*'
  # sqlite
  DJANGO_SETTINGS_MODULE: 'babybuddy.settings.base'
  # postgres
  # DJANGO_SETTINGS_MODULE: 'babybuddy.settings.docker'

service:
  port:
    port: 8000

ingress:
  enabled: false

persistence:
  data:
    enabled: false
    emptyDir: false
    mountPath: /app/data
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: false
    emptyDir: false
    mountPath: /app/media
    accessMode: ReadWriteOnce
    size: 1Gi

# Enable postgres
# https://github.com/nicholaswilde/helm-charts/blob/main/charts/postgres/values.yaml
postgres:
  enabled: false
  secret:
    POSTGRES_PASSWORD: "babybuddy-pass"
  env:
    POSTGRES_USER: "babybuddy"
    POSTGRES_DB: "babybuddy-postgres"
  fullnameOverride: babybuddy-postgres
