{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "writefreely.harcodedValues" -}}
persistence:
  writefreely-config:
    enabled: "true"
    mountPath: "/config"
    type: "custom"
    accessMode: "ReadWriteOnce"
    size: "1Gi"
    volumeSpec:
      configMap:
        name: {{ printf "%v-config" (include "common.names.fullname" .) }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "writefreely.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
