---
apiVersion: v2
appVersion: "2.7.3"
version: 0.1.21
name: smokeping
description: Keep track of your network latency.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/smokeping"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/smokeping.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - smokeping
  - network
  - latency
sources:
  - https://oss.oetiker.ch/smokeping/
  - https://hub.docker.com/r/linuxserver/smokeping
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Bump tag to 2.7.3-r5-ls127
    - kinda: changed
      description: Simplify values.yaml
    - kind: removed
      descrition: secret from values.yaml
  artifacthub.io/images: |
    - name: smokeping
      image: ghcr.io/linuxserver/smokeping:2.7.3-r5-ls127
