apiVersion: v2
appVersion: 9e30fdd7
version: 0.1.7
name: smokeping
description: Keep track of your network latency.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/smokeping"
icon: "https://raw.githubusercontent.com/nicholaswilde/helm-charts/main/charts/smokeping/img/smokeping-icon.jpg"
dependencies:
- name: common
  version: ~0.1.8
  repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - smokeping
  - network
  - latency
sources:
  - https://oss.oetiker.ch/smokeping/
  - https://hub.docker.com/r/linuxserver/smokeping
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Fixed linting issues.
    - Bumped common to ~0.1.8
  artifacthub.io/images: |
    - name: smokeping
      image: ghcr.io/linuxserver/smokeping:9e30fdd7-ls111
