---
# Default values for SmokePing
image:
  repository: ghcr.io/linuxserver/smokeping
  pullPolicy: IfNotPresent
  tag: "2.7.3-r5-ls117"
strategy:
  type: Recreate
service:
  port:
    port: 80
secret: {}
env:
  TZ: "America/Los_Angeles"
  # PUID: "1001"
  # PGID: "1001"
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
  hosts:
    - host: "smokeping.192.168.1.199.nip.io"
      paths:
        - path: "/"
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
    # existingClaim: ""
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false
