---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/headphones
  pullPolicy: IfNotPresent
  tag: "version-58edc604"

# See more environment variables in the headphones documentation
# https://github.com/linuxserver/docker-headphones#parameters
env: {}
  # TZ:

service:
  port:
    port: 8181

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
  downloads:
    enabled: false
    emptyDir: false
    mountPath: /downloads
    accessMode: ReadWriteOnce
    size: 1Gi
  music:
    enabled: false
    emptyDir: false
    mountPath: /music
    accessMode: ReadWriteOnce
    size: 1Gi
