---
apiVersion: v2
appVersion: 1.8.2
version: 1.0.1
name: hedgedoc
description: HedgeDoc lets you create real-time collaborative markdown notes.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/hedgedoc"
icon: "https://avatars1.githubusercontent.com/u/67865462"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
  - name: mariadb
    version: ~1.0.5
    repository: https://nicholaswilde.github.io/helm-charts/
    condition: mariadb.enabled
keywords:
  - hedgedoc
  - hedge
  - doc
  - markdown
  - editor
sources:
  - https://github.com/hedgedoc/hedgedoc
  - https://hub.docker.com/r/linuxserver/hedgedoc
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Change chart to version-1.8.2 in order to reduce the number of chart updates.
    - kind: changed
      description: Bump mariadb to 1.0.5
  artifacthub.io/images: |
    - name: hedgedoc
      image: ghcr.io/linuxserver/hedgedoc:version-1.8.2
