---
apiVersion: v2
appVersion: 1.7.2
version: 0.1.7
name: hedgedoc
description: HedgeDoc lets you create real-time collaborative markdown notes.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/hedgedoc"
icon: "https://avatars1.githubusercontent.com/u/67865462"
dependencies:
  - name: common
    version: ~0.1.7
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - hedgedoc
  - hedge
  - doc
  - markdown
  - editor
sources:
  - https://github.com/hedgedoc/hedgedoc
  - https://hub.docker.com/r/linuxserver/hedgedoc
maintainers:
  - name: Nicholas Wilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/images: |
    - name: hedgedoc
      image: ghcr.io/linuxserver/hedgedoc:1.7.2-ls4
