---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/sqlitebrowser
  pullPolicy: IfNotPresent
  tag: "version-3.12.2-02876202105241947ubuntu18.04.1"

# See more environment variables in the sqlitebrowser documentation
# https://github.com/linuxserver/docker-sqlitebrowser#parameters
env: {}
  # TZ:

service:
  port:
    port: 3000

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
