---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/davos
  pullPolicy: IfNotPresent
  tag: "2.2.1-ls76"

# See more environment variables in the davos documentation
# https://github.com/linuxserver/docker-davos#parameters
env: {}
  # PUID: "1000"
  # PGID: "1000"

service:
  port:
    port: 8080

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
  download:
    enabled: false
    emptyDir: false
    mountPath: /download
    accessMode: ReadWriteOnce
    size: 1Gi
