---
apiVersion: v2
appVersion: "8ad9278"
version: 0.1.2
name: haste
description: An open-source pastebin software written in Node.JS, which is easily installable in any network.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/haste"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/haste.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - haste
  - pastebin
sources:
  - https://github.com/zneix/haste-server
  - https://hub.docker.com/r/nicholaswilde/haste
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Updated artifacthub.io/images[0].image
    - Updated icon url.
  artifacthub.io/images: |
    - name: haste
      image: ghcr.io/nicholaswilde/haste:8ad9278-ls1
