---
apiVersion: v2
appVersion: v5.1.0
version: 0.2.0
name: snipe-it
description: Open source asset management
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/snipe-it"
icon: "https://pbs.twimg.com/profile_images/976748875733020672/K-HnZCCK_400x400.jpg"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - snipeit
  - snipe
  - asset
  - management
sources:
  - https://snipeitapp.com/
  - https://hub.docker.com/r/linuxserver/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - BREAKING CHANGE This release requires PHP 7.2.5 or greater. See https://github.com/linuxserver/docker-snipe-it/releases/tag/v5.1.0-ls117.
    - Bumped tag to v5.1.0-ls117
  artifacthub.io/images: |
    - name: snipe-it
      image: ghcr.io/linuxserver/snipe-it:v5.1.0-ls117
