---
apiVersion: v2
appVersion: v5.1.3
version: 0.2.6
name: snipe-it
description: Open source asset management
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/snipe-it"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/snipe-it.jpg"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - snipeit
  - snipe
  - asset
  - management
sources:
  - https://snipeitapp.com/
  - https://hub.docker.com/r/linuxserver/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bumped tag to v5.1.3-ls120
  artifacthub.io/images: |
    - name: snipe-it
      image: ghcr.io/linuxserver/snipe-it:v5.1.3-ls120
