---
apiVersion: v2
appVersion: v5.1.5
version: 0.3.0
name: snipe-it
description: Open source asset management
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/snipe-it"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/snipe-it.jpg"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
  - name: mariadb
    version: ~1.0.0
    repository: https://nicholaswilde.github.io/helm-charts/
    condition: mariadb.enabled
keywords:
  - snipeit
  - snipe
  - asset
  - management
sources:
  - https://snipeitapp.com/
  - https://hub.docker.com/r/linuxserver/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bump tag to v5.1.5-ls131
    - Add mariadb support
  artifacthub.io/images: |
    - name: snipe-it
      image: ghcr.io/linuxserver/snipe-it:v5.1.5-ls131
