---
apiVersion: v2
appVersion: "v2021.02"
version: 0.1.2
name: chyrp-lite
description: An ultra-lightweight blogging engine, written in PHP.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/chyrp-lite"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/chyrp-lite.svg"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - docker
  - chyrp
  - lite
  - blog
  - engine
  - php
  - twig
  - html5
sources:
  - https://github.com/xenocrat/chyrp-lite
  - https://github.com/nicholaswilde/docker-chyrp-lite
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bump tag to v2021.02-ls2
  artifacthub.io/images: |
    - name: chyrp-lite
      image: ghcr.io/nicholaswilde/chyrp-lite:v2021.02-ls2
