---
apiVersion: v2
appVersion: 4.14.0
version: 0.2.8
name: diun
description: Docker image update notifier
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/diun"
icon: "https://raw.githubusercontent.com/crazy-max/diun/master/.res/diun.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - docker
  - notifier
  - notification
  - image
  - update
sources:
  - https://crazymax.dev/diun/
  - https://hub.docker.com/r/crazymax/diun
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bumped tag to 4.14.0
  artifacthub.io/images: |
    - name: diun
      image: ghcr.io/crazy-max/diun:4.14.0
