---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/crazy-max/diun
  pullPolicy: IfNotPresent
  tag: "4.19.0"

secret: {}
# DIUN_NOTIF_GOTIFY_TOKEN: ""

service:
  enabled: false

# See more environment variables in the diun documentation
# https://crazymax.dev/diun/config/
env:
  TZ: "America/Los_Angeles"
  LOG_LEVEL: "info"
  LOG_JSON: "false"
  DIUN_WATCH_WORKERS: "20"
  DIUN_WATCH_SCHEDULE: "0 */12 * * *"
  # Gotify
  DIUN_NOTIF_GOTIFY_ENDPOINT: "http://gotify.192.168.1.189.nip.io/"
  DIUN_NOTIF_GOTIFY_PRIORITY: "1"
  DIUN_NOTIF_GOTIFY_TIMEOUT: "10s"
  # Kubernetes
  DIUN_PROVIDERS_KUBERNETES: "true"

rbac:
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - watch
        - list

persistence:
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi

serviceAccount:
  create: true
