---
apiVersion: v2
appVersion: 1.8.9
version: 0.1.6
name: etherpad
description: A real-time collaborative editor scalable to thousands of simultaneous real time users.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/etherpad"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/etherpad.jpg"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - etherpad
  - editor
  - notepad
  - pad
sources:
  - https://etherpad.org/
  - https://github.com/ether/etherpad-lite
  - https://hub.docker.com/r/nicholaswilde/etherpad
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Bumped tag to 1.8.9-ls3
    - Added app volume.
    - Changed icon location.
  artifacthub.io/images: |
    - name: etherpad
      image: ghcr.io/nicholaswilde/etherpad:1.8.9-ls3
