---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/photoshow
  pullPolicy: IfNotPresent
  tag: "48aabb98-ls101"

# See more environment variables in the photoshow documentation
# https://github.com/linuxserver/docker-photoshow#parameters
env: {}
  # TZ:
  # PUID: "1000"
  # PGID: "1000"

service:
  port:
    port: 80

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
  pictures:
    enabled: false
    emptyDir: false
    mountPath: /Pictures
    accessMode: ReadWriteOnce
    size: 1Gi
  thumbs:
    enabled: false
    emptyDir: false
    mountPath: /Thumbs
    accessMode: ReadWriteOnce
    size: 1Gi
