---
apiVersion: v2
appVersion: 1.2.0
version: 0.1.1
name: novnc
description: The open source VNC client
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/novnc"
icon: "https://pbs.twimg.com/profile_images/1231135026/twitter_400x400.png"
dependencies:
  - name: common
    version: ~0.1.7
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - novnc
  - vnc
  - remote
  - desktop
sources:
  - https://novnc.com/
maintainers:
  - name: Nicholas Wilde
    email: ncwilde43@gmail.com
