---
apiVersion: v2
appVersion: 1.2.0
version: 0.1.5
name: novnc
description: The open source VNC client
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/novnc"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/novnc.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - novnc
  - vnc
  - remote
  - desktop
sources:
  - https://novnc.com/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Changed icon location
  artifacthub.io/images: |
    - name: novnc
      image: ghcr.io/nicholaswilde/novnc:1.2.0-ls2
