---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/nicholaswilde/novnc
  pullPolicy: IfNotPresent
  tag: "version-1.2.0"

# See more environment variables in the novnc documentation
# https://github.com/nicholaswilde/docker-novnc
env:
  TZ: "America/Los_Angeles"
  REMOTE_HOST: "localhost"
  REMOTE_PORT: "5900"
  # PUID: "1000"
  # PGID: "1000"

service:
  port:
    port: 6080

ingress:
  enabled: false

persistence:
  app:
    enabled: false
    emptyDir: false
    mountPath: /app
    accessMode: ReadWriteOnce
    size: 1Gi
