---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/audacity
  pullPolicy: IfNotPresent
  tag: "version-3.0.2"

secret: {}

# See more environment variables in the audacity documentation
# https://github.com/linuxserver/docker-audacity#parameters
env: {}
  # TZ:

service:
  port:
    port: 3000

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
