---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/doublecommander
  pullPolicy: IfNotPresent
  tag: "version-0.8.2-1"

# See more environment variables in the doublecommander documentation
# https://github.com/linuxserver/docker-doublecommander#parameters
env: {}
  # TZ:

service:
  port:
    port: 3000

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi
