---
apiVersion: v2
appVersion: r1070
version: 1.0.1
name: projectsend
description: A self-hosted application that lets you upload files and assign them to specific clients that you create yourself
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/projectsend"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/projectsend.jpg"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
  - name: mariadb
    version: ~1.0.3
    repository: https://nicholaswilde.github.io/helm-charts/
    condition: mariadb.enabled
keywords:
  - project
  - send
  - upload
  - files
sources:
  - https://www.projectsend.org/
  - https://hub.docker.com/r/linuxserver/projectsend
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common tag to 0.1.13
    - kind: changed
      description: Bump tag to r1070-ls71
    - kind: removed
      description: secret from values.yaml
  artifacthub.io/images: |
    - name: projectsend
      image: ghcr.io/linuxserver/projectsend:r1070-ls70
