---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/projectsend
  pullPolicy: IfNotPresent
  tag: "version-r1070"

# See more environment variables in the projectsend documentation
# https://www.projectsend.org/how-to-install-projectsend/
env: {}
  # TZ:

service:
  port:
    port: 80

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
  data:
    enabled: false
    emptyDir: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi

# Enable mariadb
# https://github.com/nicholaswilde/helm-charts/blob/main/charts/mariadb/values.yaml
mariadb:
  enabled: false
  secret:
    MYSQL_ROOT_PASSWORD: "projectsend-pass"
    MYSQL_PASSWORD: "projectsend-pass"
  env:
    MYSQL_USER: "projectsend"
    MYSQL_DATABASE: "projectsend-mariadb"
  fullnameOverride: projectsend-mariadb
