---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/pixapop
  pullPolicy: IfNotPresent
  tag: "v1.2-ls15"

secret: {}

# See more environment variables in the pixapop documentation
# https://github.com/linuxserver/docker-pixapop#application-setup
env: {}
  # TZ:

service:
  port:
    port: 80

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
  photos:
    enabled: false
    emptyDir: false
    mountPath: /photos
    accessMode: ReadWriteOnce
    size: 1Gi
