---
name: "Charts: Release"

on:
  push:
    branches: 
      - main
    paths:
      - 'charts/**'
      - '!charts/**/README.md'

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.5.4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts/*
          charts_repo_url: https://nicholaswilde.github.io/helm-charts/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
