---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/muximux
  pullPolicy: IfNotPresent
  tag: "version-057352e8"

# See more environment variables in the muximux documentation
# https://github.com/linuxserver/docker-muximux#parameters
env: {}
  # TZ:

service:
  port:
    port: 80

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
